# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d7ecf25d2aace256667fa4878280f07683e1a9426fe676681892f4ab01726fe96a9a60290ca4d7b00d19da8ea576fc12dc316941fef38702002f42b56a5ec95

test:
  secret_key_base: 7581463b8ced51cbe3de76cb1fa1502319539f979a9e79fbbf8e8be789c24d647bd3d74d91b4a3ce0ec4d6f904e3d74f38d72486b842ee6b2215f62260a954bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
